package wizard

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
)

func TestAliasField_inlineErrorSurvivesRefresh(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	if err := os.WriteFile(cfg, []byte("Host existing\n  HostName 1.2.3.4\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	host := "10.0.0.1"
	f := NewAliasField(cfg, &host).Value(new(string))
	f.focused = true
	f.textinput.SetValue("existing")

	model, _ := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if field.inlineMsg == "" {
		t.Fatal("want inline conflict message after Enter")
	}

	model, _ = field.Update(struct{}{})
	field = model.(*aliasField)
	if field.inlineMsg == "" {
		t.Fatal("inline conflict message should survive refresh update")
	}
}

func TestAliasField_rejectsConflictInline(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	if err := os.WriteFile(cfg, []byte("Host existing\n  HostName 1.2.3.4\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	host := "10.0.0.1"
	f := NewAliasField(cfg, &host).Value(new(string))
	f.textinput.SetValue("existing")
	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if cmd != nil {
		t.Fatal("want no advance on conflict")
	}
	if field.inlineMsg == "" {
		t.Fatal("want inline conflict message")
	}
	if !strings.Contains(field.inlineMsg, "existing") {
		t.Fatalf("inlineMsg = %q, want mention existing", field.inlineMsg)
	}
}

func TestAliasField_rejectsAutoGeneratedConflict(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	if err := os.WriteFile(cfg, []byte("Host 100-0-0-1\n  HostName old\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	host := "100.0.0.1"
	f := NewAliasField(cfg, &host).Value(new(string))
	f.focused = true
	f.textinput.SetValue("")

	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if cmd != nil {
		t.Fatal("want no advance when auto-generated alias conflicts")
	}
	if field.inlineMsg == "" {
		t.Fatal("want inline conflict for empty input with conflicting default alias")
	}
}

func TestAliasField_normalizesOnEnter(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	host := "10.0.0.2"
	alias := ""

	f := NewAliasField(cfg, &host).Value(&alias)
	f.textinput.SetValue("my_vps")
	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if cmd == nil {
		t.Fatal("want NextField on valid alias")
	}
	if field.textinput.Value() != "my-vps" {
		t.Errorf("textinput = %q, want my-vps", field.textinput.Value())
	}
	if alias != "my-vps" {
		t.Errorf("accessor alias = %q, want my-vps", alias)
	}
}

func TestAliasField_allowsNewAlias(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	host := "10.0.0.2"
	alias := "my-vps"

	f := NewAliasField(cfg, &host).Value(&alias)
	f.textinput.SetValue("my-vps")
	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if field.inlineMsg != "" {
		t.Fatalf("unexpected inline error: %q", field.inlineMsg)
	}
	if cmd == nil {
		t.Fatal("want NextField cmd on valid alias")
	}
}

func TestAliasField_placeholderFromHost(t *testing.T) {
	host := "203.0.113.10"
	f := NewAliasField(t.TempDir()+"/cfg", &host).Value(new(string))
	f.View()
	if f.textinput.Placeholder != "203-0-113-10" {
		t.Errorf("placeholder = %q, want 203-0-113-10", f.textinput.Placeholder)
	}
}

func TestAliasField_autoFillsOnEnterWhenEmpty(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	host := "203.0.113.10"
	alias := ""

	f := NewAliasField(cfg, &host).Value(&alias)
	f.textinput.SetValue("")
	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if cmd == nil {
		t.Fatal("want NextField when auto alias is valid")
	}
	if field.textinput.Value() != "203-0-113-10" {
		t.Errorf("textinput = %q, want 203-0-113-10", field.textinput.Value())
	}
	if alias != "203-0-113-10" {
		t.Errorf("alias = %q, want 203-0-113-10", alias)
	}
}

func TestAliasPlaceholder_updatesWithHost(t *testing.T) {
	host := "1.2.3.4"
	if got := aliasPlaceholder(host); got != "1-2-3-4" {
		t.Errorf("aliasPlaceholder = %q, want 1-2-3-4", got)
	}
	host = ""
	if got := aliasPlaceholder(host); got == "1-2-3-4" {
		t.Errorf("empty host should not show old preview, got %q", got)
	}
}
