package wizard

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	tea "github.com/charmbracelet/bubbletea"
)

func TestAliasField_inlineErrorSurvivesRefresh(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	if err := os.WriteFile(cfg, []byte("Host existing\n  HostName 1.2.3.4\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	host := "10.0.0.1"
	f := NewAliasField(cfg, &host).Value(new(string))
	f.focused = true
	f.textinput.SetValue("existing")

	model, _ := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if field.inlineMsg == "" {
		t.Fatal("want inline conflict message after Enter")
	}

	// 模拟 huh 在同一次按键后发送的 refresh 消息，错误提示必须保留。
	model, _ = field.Update(struct{}{})
	field = model.(*aliasField)
	if field.inlineMsg == "" {
		t.Fatal("inline conflict message should survive refresh update")
	}
}

func TestAliasField_rejectsConflictInline(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	if err := os.WriteFile(cfg, []byte("Host existing\n  HostName 1.2.3.4\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	host := "10.0.0.1"
	f := NewAliasField(cfg, &host).Value(new(string))
	f.textinput.SetValue("existing")
	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if cmd != nil {
		t.Fatal("want no advance on conflict")
	}
	if field.inlineMsg == "" {
		t.Fatal("want inline conflict message")
	}
	if !strings.Contains(field.inlineMsg, "existing") {
		t.Fatalf("inlineMsg = %q, want mention existing", field.inlineMsg)
	}
}

func TestAliasField_rejectsAutoGeneratedConflict(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	if err := os.WriteFile(cfg, []byte("Host 100-0-0-1\n  HostName old\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	host := "100.0.0.1" // NormalizeHostAlias -> 100-0-0-1，与 config 中已有别名冲突
	f := NewAliasField(cfg, &host).Value(new(string))
	f.focused = true
	f.textinput.SetValue("")

	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if cmd != nil {
		t.Fatal("want no advance when auto-generated alias conflicts")
	}
	if field.inlineMsg == "" {
		t.Fatal("want inline conflict for empty input with conflicting default alias")
	}
}

func TestAliasField_normalizesOnEnter(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	host := "10.0.0.2"
	alias := ""

	f := NewAliasField(cfg, &host).Value(&alias)
	f.textinput.SetValue("my_vps")
	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if cmd == nil {
		t.Fatal("want NextField on valid alias")
	}
	if field.textinput.Value() != "my-vps" {
		t.Errorf("textinput = %q, want my-vps", field.textinput.Value())
	}
	if alias != "my-vps" {
		t.Errorf("accessor alias = %q, want my-vps", alias)
	}
}

func TestAliasField_allowsNewAlias(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "config")
	host := "10.0.0.2"
	alias := "my-vps"

	f := NewAliasField(cfg, &host).Value(&alias)
	f.textinput.SetValue("my-vps")
	model, cmd := f.Update(tea.KeyMsg{Type: tea.KeyEnter})
	field := model.(*aliasField)
	if field.inlineMsg != "" {
		t.Fatalf("unexpected inline error: %q", field.inlineMsg)
	}
	if cmd == nil {
		t.Fatal("want NextField cmd on valid alias")
	}
}
